import { defineOrvalConfig } from './defineOrvalConfig';

const STANDARD_OPTS = {
  swaggerDir: './src/server/swagger',
  outDir: './src/server/autoGeneratedHooks',
  mutatorPath: './src/server/mutators',
};

describe('defineOrvalConfig', () => {
  it('produces an entry for each of the six services', () => {
    const config = defineOrvalConfig(STANDARD_OPTS);
    expect(Object.keys(config)).toEqual([
      'onlineMenuApi',
      'identityApi',
      'questionerApi',
      'contentApi',
      'paymentApi',
      'notificationApi',
    ]);
  });

  it('wires the onlineMenu entry exactly as the legacy config did', () => {
    const config = defineOrvalConfig(STANDARD_OPTS);
    expect(config.onlineMenuApi).toEqual({
      input: {
        target: './src/server/swagger/onlinemenu.json',
        validation: false,
      },
      output: {
        target: './src/server/autoGeneratedHooks/onlinemenu/index.ts',
        client: 'react-query',
        mode: 'tags-split',
        clean: true,
        prettier: true,
        schemas: './src/server/autoGeneratedHooks/onlinemenu/models',
        override: {
          mutator: {
            path: './src/server/mutators/onlineMenuMutator.ts',
            name: 'customInstance',
          },
        },
      },
      hooks: {
        afterAllFilesWrite: [
          {
            command:
              'npx prettier --write ./src/server/autoGeneratedHooks/onlinemenu',
          },
          { command: 'echo "✅ Orval: OnlineMenuSaaS hooks generated"' },
        ],
      },
    });
  });

  it('maps each service to its mutator name', () => {
    const config = defineOrvalConfig(STANDARD_OPTS);
    expect(config.identityApi?.output.override.mutator.name).toBe('identityInstance');
    expect(config.questionerApi?.output.override.mutator.name).toBe('questionerInstance');
    expect(config.contentApi?.output.override.mutator.name).toBe('contentInstance');
    expect(config.paymentApi?.output.override.mutator.name).toBe('paymentInstance');
    expect(config.notificationApi?.output.override.mutator.name).toBe('notificationInstance');
  });

  it('routes the schemas dir under the per-service generated dir', () => {
    const config = defineOrvalConfig(STANDARD_OPTS);
    expect(config.contentApi?.output.schemas).toBe(
      './src/server/autoGeneratedHooks/content/models',
    );
  });

  it('normalizes trailing/leading slashes in supplied paths', () => {
    const config = defineOrvalConfig({
      swaggerDir: './src/server/swagger/',
      outDir: './src/server/autoGeneratedHooks/',
      mutatorPath: '/src/server/mutators/',
    });
    expect(config.onlineMenuApi?.input.target).toBe(
      './src/server/swagger/onlinemenu.json',
    );
    expect(config.onlineMenuApi?.output.target).toBe(
      './src/server/autoGeneratedHooks/onlinemenu/index.ts',
    );
    expect(config.onlineMenuApi?.output.override.mutator.path).toBe(
      '/src/server/mutators/onlineMenuMutator.ts',
    );
  });

  it('honors an explicit prettier=false override', () => {
    const config = defineOrvalConfig({ ...STANDARD_OPTS, prettier: false });
    expect(config.onlineMenuApi?.output.prettier).toBe(false);
  });

  it('defaults prettier to true when omitted', () => {
    const config = defineOrvalConfig(STANDARD_OPTS);
    expect(config.notificationApi?.output.prettier).toBe(true);
  });
});
