/**
 * Orval config factory shared by erevna-web and katalogos-web.
 *
 * Both apps generate React Query hooks from the SAME six OpenAPI services
 * (onlineMenu / identity / questioner / content / notification / payment) with
 * an identical `tags-split` + per-service-mutator setup. This factory owns that
 * shared shape; each app supplies only its own paths via {@link DefineOrvalConfigOptions}.
 *
 * The return value is a plain Orval config object (the same thing
 * `defineConfig(...)` returns), so the app's `orval.config.js` becomes:
 *
 * ```js
 * const { defineOrvalConfig } = require('@dloizides/orval-preset');
 * module.exports = defineOrvalConfig({
 *   swaggerDir: './src/server/swagger',
 *   outDir: './src/server/autoGeneratedHooks',
 *   mutatorPath: './src/server/mutators',
 * });
 * ```
 */

export interface DefineOrvalConfigOptions {
  /** Directory holding the per-service swagger JSON inputs (app-owned). */
  swaggerDir: string;
  /** Directory the generated client dirs are written to (app-owned, gitignored). */
  outDir: string;
  /** Directory holding the mutator files orval points generated hooks at (app-owned shims). */
  mutatorPath: string;
  /** Optional prettier override (defaults to true, matching the legacy config). */
  prettier?: boolean;
}

interface OrvalMutatorOverride {
  path: string;
  name: string;
}

interface OrvalHookCommand {
  command: string;
}

interface OrvalApiEntry {
  input: {
    target: string;
    validation: boolean;
  };
  output: {
    target: string;
    client: 'react-query';
    mode: 'tags-split';
    clean: boolean;
    prettier: boolean;
    schemas: string;
    override: {
      mutator: OrvalMutatorOverride;
    };
  };
  hooks: {
    afterAllFilesWrite: OrvalHookCommand[];
  };
}

export type OrvalConfig = Record<string, OrvalApiEntry>;

interface ApiDescriptor {
  /** Orval config key (e.g. `onlineMenuApi`). */
  key: string;
  /** Swagger file basename without extension + the generated dir name (e.g. `onlinemenu`). */
  slug: string;
  /** Mutator file basename without extension (e.g. `onlineMenuMutator`). */
  mutatorFile: string;
  /** Exported mutator function name (e.g. `customInstance`). */
  mutatorName: string;
  /** Human label used in the generated success echo. */
  label: string;
}

// The six services both apps generate, in the legacy config's order.
const API_DESCRIPTORS: readonly ApiDescriptor[] = [
  {
    key: 'onlineMenuApi',
    slug: 'onlinemenu',
    mutatorFile: 'onlineMenuMutator',
    mutatorName: 'customInstance',
    label: 'OnlineMenuSaaS',
  },
  {
    key: 'identityApi',
    slug: 'identity',
    mutatorFile: 'identityMutator',
    mutatorName: 'identityInstance',
    label: 'IdentityService',
  },
  {
    key: 'questionerApi',
    slug: 'questioner',
    mutatorFile: 'questionerMutator',
    mutatorName: 'questionerInstance',
    label: 'QuestionerService',
  },
  {
    key: 'contentApi',
    slug: 'content',
    mutatorFile: 'contentMutator',
    mutatorName: 'contentInstance',
    label: 'ContentService',
  },
  {
    key: 'paymentApi',
    slug: 'payment',
    mutatorFile: 'paymentMutator',
    mutatorName: 'paymentInstance',
    label: 'PaymentService',
  },
  {
    key: 'notificationApi',
    slug: 'notification',
    mutatorFile: 'notificationMutator',
    mutatorName: 'notificationInstance',
    label: 'NotificationService',
  },
];

/** Strips trailing forward slashes without a backtracking-prone regex. */
function stripTrailingSlashes(value: string): string {
  let end = value.length;
  while (end > 0 && value[end - 1] === '/') {
    end -= 1;
  }
  return value.slice(0, end);
}

/**
 * Joins a base dir to a segment with a single forward slash. The base may carry
 * a trailing slash (app paths often do); segments are always clean slugs/files.
 */
function joinPath(base: string, segment: string): string {
  return `${stripTrailingSlashes(base)}/${segment}`;
}

function buildApiEntry(
  descriptor: ApiDescriptor,
  options: Required<Pick<DefineOrvalConfigOptions, 'swaggerDir' | 'outDir' | 'mutatorPath' | 'prettier'>>,
): OrvalApiEntry {
  const generatedDir = joinPath(options.outDir, descriptor.slug);
  return {
    input: {
      target: joinPath(options.swaggerDir, `${descriptor.slug}.json`),
      validation: false,
    },
    output: {
      target: joinPath(generatedDir, 'index.ts'),
      client: 'react-query',
      mode: 'tags-split',
      clean: true,
      prettier: options.prettier,
      schemas: joinPath(generatedDir, 'models'),
      override: {
        mutator: {
          path: joinPath(options.mutatorPath, `${descriptor.mutatorFile}.ts`),
          name: descriptor.mutatorName,
        },
      },
    },
    hooks: {
      afterAllFilesWrite: [
        { command: `npx prettier --write ${generatedDir}` },
        { command: `echo "✅ Orval: ${descriptor.label} hooks generated"` },
      ],
    },
  };
}

/**
 * Builds the shared 6-API Orval config object from app-supplied paths.
 */
export function defineOrvalConfig(options: DefineOrvalConfigOptions): OrvalConfig {
  const resolved = {
    swaggerDir: options.swaggerDir,
    outDir: options.outDir,
    mutatorPath: options.mutatorPath,
    prettier: options.prettier ?? true,
  };

  const config: OrvalConfig = {};
  for (const descriptor of API_DESCRIPTORS) {
    config[descriptor.key] = buildApiEntry(descriptor, resolved);
  }
  return config;
}
